spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/submission
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
management:
  security:
    enabled: false  

logging:
  level:
    com.stckroute.submission-service: DEBUG


